vim.g.mapleader = " "

vim.cmd("set expandtab")
vim.api.nvim_set_keymap("n", "<leader>fw", ":w<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>wv", "<C-W><C-V>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>wh", "<C-W><C-n>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>j", "<C-W>J", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>r", "<C-W>r", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>h", "<C-W>H", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>k", "<C-W>K", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "\\<leader>l", "<C-W>l", { noremap = true, silent = true })

vim.api.nvim_set_keymap("n", "<leader>fq", ":wqa<CR>", { noremap = true, silent = true })
vim.cmd("setlocal spell spelllang=en_us")
vim.cmd("set number")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("nmap < v<")
vim.cmd("nmap > v>")
vim.cmd("imap jk <Esc>")
vim.cmd("nmap T <CMD>BufferPrevious<CR>")

vim.cmd("nmap tn <CMD>BufferNext<CR>")
vim.cmd("nmap tp <CMD>BufferPrevious<CR>")
vim.cmd("nnoremap tc :tabclose<CR>")
vim.cmd("nmap <leader>wq :wq<CR>:qa<CR>")
vim.cmd("nmap <leader><CR> <C-w>l")
function man(args)
	os.execute("man " + args[0])
end
vim.api.nvim_create_user_command("Man", man, { count = 1 })
